### ISSUE TITLE
check license

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#17]
Currently, we are using two open data sources for this course:

- Sentinel-2 images, [according to ESA](https://open.esa.int/copernicus-sentinel-satellite-imagery-under-open-licence/) it has a [CC BY-SA 3.0 IGO](https://creativecommons.org/licenses/by-sa/3.0/igo/) license

- PDOK vector data: [according to PDOK](https://www.pdok.nl/copyright) it has a [CC-BY-4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.nl) license

We need to confirm with the Carpentry Incubator community that this license is okay.

**Comment by rogerkuou** [comment]
Hi @rbavery , not sure if I have checked this with you before (sorry if I did and forgot). In this issue, we listed the license of data we have used in this course. Do you know how should we check if this complies with the Carpentry course standard?

**Comment by tobyhodges** [comment]
Thanks @rbavery for pointing me to this thread.

The CC BY-SA license is not compatible with the CC-BY license for a lesson, and I cannot recommend that you use data licensed that way here. It will prevent others from being able to freely reuse and adapt the lesson for other settings where e.g. an open license is not appropriate.

Data licensed CC-BY is not ideal - [the BY part is potentially meaningless for data, depending on the region, and likely to confuse users wishing to adapt the lesson](https://osc.universityofcalifornia.edu/2016/09/cc-by-and-data-not-always-a-good-fit/) - but seems to be very prevalent despite this. Ideally, data used in Incubator lessons should be in the public domain, i.e. CC0. But CC-BY is compatible with the license of the lessons, at least, so we can let it pass if there is no public domain alternative that you can easily use.

[Dryad provides a good summary of why CC0 is the best choice for open data](https://blog.datadryad.org/2011/10/05/why-does-dryad-use-cc0/)

**Comment by rbavery** [comment]
Thanks for this info @tobyhodges . Unfortunately there's not a lot of freely available public satellite imagery to download, even fewer that are hosted as cloud optimized datasets that can be easily accessed over HTTP. We initially went with Landsat, which is the one other constellation that matches Sentinel-2's public reach and impact, but that data source changed on us so we switched to this one for more stability.

For what it is worth, from reading this FAQ, it seems that this license is targeted more toward folks in media: https://open.esa.int/image-usage-creative-commons/ not education. 

I don't think there are any satellite datasets in the public domain that we could use for this lesson. At least not any that the average learner would have familiarity with and not any that could be accessed over HTTP from a cloud provider. Given that, does the use of these licenses mean that we wouldn't be able to get this lesson officially approved? Or could it still conceivably advance to beta?

**Comment by rbavery** [comment]
I'm happy to reach out to Copernicus for clarification on their license as well and how it affects the overall licensing for this lesson. It sounds like they do have a system for distributing waivers. I hope that wouldn't be necessary but don't have a problem asking since the use of Sentinel-2 for this lesson is pretty fundamental. The richness of the dataset allows for a lot of opportunity for growth in the lesson content in the future and the fact that it is cloud hosted by multiple providers means it's very accessible to users inside this lesson and out in the real world (they'll likely work with this dataset again).

**Comment by tobyhodges** [comment]
I guess this is probably ok, because the data is not directly included in this repository. However, I ask that you include a note (perhaps in Instructor Notes?) about the license of the data, and include a link to that answer in their FAQ page, so that people who fork and adapt your lesson understand that the Sentinel-2 data may not be as freely-modifiable as the lesson content itself. If you are happy to contact them and ask for a waiver to use it CC-BY in this lesson, I would of course prefer that.

**Comment by rbavery** [comment]
Great thanks for this clarification @tobyhodges . I'll reach out to ESA about a waiver and post an update after a week or so. If we get no response or denied we will include the note.

CC @rogerkuou

**Comment by fnattino** [comment]
Sorry for joining late the discussion, and thanks everyone for checking out the compatibility of the image and lesson licences. 

I had a further look at the material provided by ESA with respect to licenses. I now seem to understand that the CC BY-SA license referred to as above applies to ["processed public images made available by ESA"](https://open.esa.int/copernicus-sentinel-satellite-imagery-under-open-licence/), while a different policy actually applies to the Copernicus Sentinel satellite data that we are using in the lesson (see general information on the  policy [here](https://open.esa.int/copernicus-sentinel-satellite-data/) and specific license [here](https://sentinel.esa.int/documents/247904/690755/Sentinel_Data_Legal_Notice)).

It's my understanding that according to this license we have free access to Copernicus satellite data for "(a) reproduction; (b) distribution; (c) communication to the public; (d) adaptation, modification and combination with other data and information; (e) any combination of points (a) to (d)."

However, we seems to be required to add a notice where displaying the satellite data:

"Where the user communicates to the public or distributes Copernicus Sentinel Data and Service Information, he/she shall inform the recipients of the source of that Data and Information by using the following notice5:
(1) 'Copernicus Sentinel data [Year]' for Sentinel data;"

and, for the images that include adaptation/modification (cropping?):

"Where the Copernicus Sentinel Data and Service Information have been adapted or modified, the user shall provide the following notice:
(1) 'Contains modified Copernicus Sentinel data [Year]' for Sentinel data;"

**Comment by rbavery** [comment]
I think this requirement is more for media communications and not for science oriented, educational material. I'll try and get a waiver for this requirement. Realistically I don't think every scientific paper that uses Sentinel-2 data uses, or is expected to use, this notice.

**Comment by rbavery** [comment]
I think @fnattino is correct that the open access pages are not current and applicable to this lesson. I contacted the person who used to run the program and he said:

> unfortunately, the ESA Open Access Communications project which I used to run has been suspended already a few years ago.
> 
> However, I believe https://sentinel.esa.int/web/sentinel/faq and the page’s links will provide all the info you need.
> 

that page links https://sentinel.esa.int/documents/247904/690755/Sentinel_Data_Legal_Notice/ which is the same doc @fnattino linked above. I contacted EOSupport@copernicus.esa.int to try and get a waiver from this.

**Comment by rbavery** [comment]
No responses from ESA.

We currently link to ESA in this initial page, and I would prefer to cite them on this page and the setup page, but not for every single plot that uses their sat imagery (since no one does this in papers, blog posts, etc. only journalists for media sites). We could cite the legal notice directly instead of the esa webpage: https://carpentries-incubator.github.io/geospatial-python/ and include the text in the initial page and setup page

> (1) 'Copernicus Sentinel data [Year]' for Sentinel data; and/or
> (2) 'Copernicus Service information [Year]' for Copernicus Service
> Information.

**Comment by rogerkuou** [comment]
With the findings and discussions we have, I think the conclusion is the license situation is okay. Will close this issue since.
